// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzlQIQggxamxQvw6hWkOmkG199h_-1lgY',
    appId: '1:798205149245:web:81ff6ee9529b691c0b2a54',
    messagingSenderId: '798205149245',
    projectId: 'myydoctor-cb5da',
    authDomain: 'myydoctor-cb5da.firebaseapp.com',
    databaseURL: 'https://myydoctor-cb5da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myydoctor-cb5da.appspot.com',
    measurementId: 'G-S7ZN1L3J3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkVhEgRE5qX8o_T5prxp8O5KSIeyRpE4M',
    appId: '1:798205149245:android:7575afde6af4eb970b2a54',
    messagingSenderId: '798205149245',
    projectId: 'myydoctor-cb5da',
    databaseURL: 'https://myydoctor-cb5da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myydoctor-cb5da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhlOcQXN9LVRHKBp10RQyq985axTN3u4k',
    appId: '1:798205149245:ios:949c42883ac7654e0b2a54',
    messagingSenderId: '798205149245',
    projectId: 'myydoctor-cb5da',
    databaseURL: 'https://myydoctor-cb5da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myydoctor-cb5da.appspot.com',
    iosClientId: '798205149245-qna355i8a7tulkbjfb6us5emn3kmscbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myydoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhlOcQXN9LVRHKBp10RQyq985axTN3u4k',
    appId: '1:798205149245:ios:949c42883ac7654e0b2a54',
    messagingSenderId: '798205149245',
    projectId: 'myydoctor-cb5da',
    databaseURL: 'https://myydoctor-cb5da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myydoctor-cb5da.appspot.com',
    iosClientId: '798205149245-qna355i8a7tulkbjfb6us5emn3kmscbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myydoctor',
  );
}
